import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import styled from "./page.module.css";
import { usePathname } from "next/navigation";
import { MainNavigation } from "@/components/MainNavigation/MainNavigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Rent a car",
  description: "Generated by create next app",
};

export default function RootLayout(props) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={styled.container}>
          <MainNavigation />
        </div>
        {props.children}
        {props.modal}
      </body>
    </html>
  );
}
